[package]
name = "keepass-diff"
description = "This CLI-tool reads two Keepass (.kdbx) files and prints their differences."
keywords = ["cli", "diff", "keepass"]
repository = "https://github.com/Narigo/keepass-diff"
license = "MIT"
readme = "README.md"
version = "0.3.1"
authors = ["Joern Bernhardt <joern.bernhardt@googlemail.com>"]

# See https://crates.io/category_slugs
categories = ["command-line-utilities"]

exclude = [
  "docs/*"
]

[dependencies]
clap = "2.33.0"
keepass = "0.4.4"
rpassword = "4.0.1"
termcolor = "1.0.5"
