name: Run checks

on: pull_request

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Run integration tests 🏘
        run: |
          ./run_tests.sh
